# theme = "gruvbox_light_soft"
# theme = "rose_pine"
theme = "kinda_nvim_patched"
# theme = "material_deep_ocean"
# theme = "material_oceanic"
# theme = "noctis"
# theme = "ferra"
# theme = "cyan_light"
# theme = "tokyonight"
# theme = "tokyonight_darkest"

[editor]
line-number = "relative"
cursorline = true
# rulers = [80]
rulers = [120]
text-width = 120
bufferline = "always"
# bufferline = "multiple"
# popup-border = "none"
popup-border = "all"
shell = ["bash", "-c"]
# shell = ["fish", "-c"]
# shell = ["sh", "-c"]

[editor.cursor-shape]
insert = "block"
normal = "underline"
# normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "spacer", "version-control"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "N („• ᴗ •„)"
mode.insert = "I ｡ﾟ･ (>﹏<) ･ﾟ｡"
mode.select = "S (｡•̀ᴗ-)✧☆*:・ﾟ"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

# [editor.gutters.line-numbers]
# min-width = 24

[keys.normal.space]
z = [":toggle gutters.line-numbers.min-width 24 3"]
c = ":buffer-close"
C = ":buffer-close!"
f = "file_picker_in_current_directory"
F = "file_picker"
m = ':set soft-wrap.wrap-at-text-width true'

[keys.normal.space.B]
b = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}" # Show blame info for current line

[keys.normal]
C-e = ["scroll_down","scroll_down","scroll_down"]
C-y = ["scroll_up", "scroll_up", "scroll_up"]
0 = ["goto_line_start"]
'^' = ["goto_line_start"]
'$' = ["goto_line_end"]
'A-w' = ["move_next_sub_word_start"]
'A-e' = ["move_next_sub_word_end"]
'A-b' = ["move_prev_sub_word_start"]
'A-[' = [":buffer-previous"]
'A-]' = [":buffer-next"]
x = "select_line_below"
X = "select_line_above"

[keys.select]
'A-w' = ["extend_next_sub_word_start"]
'A-e' = ["extend_next_sub_word_end"]
'A-b' = ["extend_prev_sub_word_start"]

