# theme = "gruvbox_light_soft"
# theme = "rose_pine"
theme = "kinda_nvim_patched"
# theme = "passarinho"
# theme = "material_deep_ocean"
# theme = "material_oceanic"
# theme = "noctis"
# theme = "ferra"
# theme = "cyan_light"
# theme = "tokyonight"
# theme = "tokyonight_darkest"

[editor]
line-number = "relative"
cursorline = true
rulers = [120]
text-width = 120
bufferline = "always"
popup-border = "all"
shell = ["zsh", "-c"]

[editor.lsp]
display-inlay-hints = false

[editor.cursor-shape]
insert = "block"
normal = "underline"
# normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "spacer", "version-control"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "N („• ᴗ •„)"
mode.insert = "I ⊹₊ (>﹏<) ₊⊹"
mode.select = "S (｡•̀ᴗ-)✧☆*:・ﾟ"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

# [editor.gutters.line-numbers]
# min-width = 24

[keys.normal.space]
z = [":toggle gutters.line-numbers.min-width 24 3"]
c = ":buffer-close"
C = ":buffer-close!"
f = "file_picker_in_current_directory"
F = "file_picker"

# copy current file/dir
[keys.normal.space."`"]
"\t" = "@ File path"
"f" = ":sh echo -n %{buffer_name}:%{cursor_line} | pbcopy"
"d" = ":sh dirname %{buffer_name}:%{cursor_line} | pbcopy"

# --------------------------------
# ----------- CONFIG -------------
# --------------------------------
[keys.normal.space."\\"]
"\t" = "@ Config"
r = [":config-reload", ":lsp-restart", ":reload-all"]
i = ":toggle lsp.display-inlay-hints"

# --------------------------------
# ------------- GIT --------------
# --------------------------------
[keys.normal.space.B]
"\t" = "@ Git"
b = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}" #  `| tee >(pbcopy)`
B = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name} | awk '{ print $1 }' | read hash; echo \"$(git config --get remote.origin.url | sed \"s/\\.git$//\")/-/commit/$hash\" | xargs open"

# --------------------------------
# ------------ VIEW --------------
# --------------------------------
[keys.normal.z]
s = ":toggle soft-wrap.enable"

[keys.normal.space.n]
e = ":pipe nu --stdin -c '^nu -c ($in | str trim)'"

[keys.normal]
C-e = ["scroll_down","scroll_down","scroll_down"]
C-y = ["scroll_up", "scroll_up", "scroll_up"]
0 = ["goto_line_start"]
'^' = ["goto_line_start"]
'$' = ["goto_line_end"]
'A-w' = ["move_next_sub_word_start"]
'A-e' = ["move_next_sub_word_end"]
'A-b' = ["move_prev_sub_word_start"]
'A-[' = [":buffer-previous"]
'A-]' = [":buffer-next"]
x = "select_line_below"
X = "select_line_above"
'*' = ["search_selection"]
'A-*' = ["search_selection_detect_word_boundaries"]
'C-a' = "@miw:pipe ~/dev/cycle/cycle<ret>"
'C-x' = "@miw:pipe ~/dev/cycle/cycle --prev<ret>"
'-' = ["copy_between_registers"]

[keys.select]
'A-w' = ["extend_next_sub_word_start"]
'A-e' = ["extend_next_sub_word_end"]
'A-b' = ["extend_prev_sub_word_start"]
'C-a' = "@miw:pipe cycle<ret>"
'C-x' = "@miw:pipe cycle --prev<ret>"

# --------------------------------
# ----------- BUFFERS ------------
# --------------------------------

[keys.normal.g]
n = ["no_op"]
p = ["no_op"]

[keys.normal."["]
"[" = ":buffer-previous"
[keys.normal."]"]
"]" = ":buffer-next"
[keys.normal."\\"]
"\\" = ":buffer-close"


